bitcoin:
  network: testnet
  url: https://distinguished-intensive-frost.btc-testnet.quiknode.pro/38d0f064dc8e72fe44d8a9a762d448bc64c54619/
  username: ""
  password: ""
  wallet: test_wallet

key_manager:
  network: testnet
  mnemonic_sentence: ""
  mnemonic_passphrase: ""

key_storage:
  password: secret_password_1
  path: /tmp/testnet/wallet/keys.db

storage:
  path: /tmp/testnet/wallet/storage.db

wallet:
  receive_key: cUVFBGCCjw5JGY2DUY5HTtKoHevMHs675aFkXVLvXeE4jV7GPeGb
  change_key: cVTMy1VXsEqT4z3nT3w8vupAmqBTjZBmyyE38TYP9kju9rQWpK9F
  db_path: /tmp/testnet/wallet/wallet.db
  start_height: 4631993